### City Images

POST http://{{host}}:{{port}}/city/Guimarães
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="cityImage"; filename="Guimarães.png"

< Guimarães.png
--WebAppBoundary--

###

POST http://{{host}}:{{port}}/city/Barcelona
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="cityImage"; filename="Barcelona.png"

< Barcelona.png
--WebAppBoundary--

###

POST http://{{host}}:{{port}}/city/Madrid
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="cityImage"; filename="Madrid.png"

< Madrid.png
--WebAppBoundary--

###

POST http://{{host}}:{{port}}/city/Lisbon
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="cityImage"; filename="Lisbon.png"

< Lisbon.png
--WebAppBoundary--

###

POST http://{{host}}:{{port}}/city/Paris
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="cityImage"; filename="Paris.png"

< Paris.png
--WebAppBoundary--

###

POST http://{{host}}:{{port}}/city/Rome
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="cityImage"; filename="Rome.png"

< Rome.png
--WebAppBoundary--

###

POST http://{{host}}:{{port}}/city/Tokyo
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="cityImage"; filename="Tokyo.png"

< Tokyo.png
--WebAppBoundary--

###





### USERS

POST http://{{host}}:{{port}}/sign_up
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: */*

--WebAppBoundary
Content-Type: application/json
Content-Disposition: form-data; name="user"

{
  "username": "userA",
  "password": "user",
  "email": "userA@gmail.com",
  "phoneNumber": "910000000",
  "dateOfBirth": "1998-01-01",
  "aboutMe": "I'm user A"
}
--WebAppBoundary
Content-Disposition: form-data; name="profileImage"; filename="user.png"

< user.png
--WebAppBoundary--

###

POST http://{{host}}:{{port}}/sign_up
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: */*

--WebAppBoundary
Content-Type: application/json
Content-Disposition: form-data; name="user"

{
  "username": "userB",
  "password": "user",
  "email": "userB@gmail.com",
  "phoneNumber": "910000001",
  "dateOfBirth": "1998-01-01",
  "aboutMe": "I'm user B"
}
--WebAppBoundary
Content-Disposition: form-data; name="profileImage"; filename="user.png"

< user.png
--WebAppBoundary--

###

POST http://{{host}}:{{port}}/sign_up
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: */*

--WebAppBoundary
Content-Type: application/json
Content-Disposition: form-data; name="user"

{
  "username": "userC",
  "password": "user",
  "email": "userC@gmail.com",
  "phoneNumber": "910000002",
  "dateOfBirth": "1998-01-01",
  "aboutMe": "I'm user C"
}
--WebAppBoundary
Content-Disposition: form-data; name="profileImage"; filename="user.png"

< user.png
--WebAppBoundary--

###

POST http://{{host}}:{{port}}/sign_up
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: */*

--WebAppBoundary
Content-Type: application/json
Content-Disposition: form-data; name="user"

{
  "username": "userD",
  "password": "user",
  "email": "userD@gmail.com",
  "phoneNumber": "910000003",
  "dateOfBirth": "1998-01-01",
  "aboutMe": "I'm user D"
}
--WebAppBoundary
Content-Disposition: form-data; name="profileImage"; filename="user.png"

< user.png
--WebAppBoundary--

###

POST http://{{host}}:{{port}}/sign_up
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: */*

--WebAppBoundary
Content-Type: application/json
Content-Disposition: form-data; name="user"

{
  "username": "userE",
  "password": "user",
  "email": "userE@gmail.com",
  "phoneNumber": "910000004",
  "dateOfBirth": "1998-01-01",
  "aboutMe": "I'm user E"
}
--WebAppBoundary
Content-Disposition: form-data; name="profileImage"; filename="user.png"

< user.png
--WebAppBoundary--

###

POST http://{{host}}:{{port}}/sign_up
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: */*

--WebAppBoundary
Content-Type: application/json
Content-Disposition: form-data; name="user"

{
  "username": "userF",
  "password": "user",
  "email": "userF@gmail.com",
  "phoneNumber": "910000005",
  "dateOfBirth": "1998-01-01",
  "aboutMe": "I'm user F"
}
--WebAppBoundary
Content-Disposition: form-data; name="profileImage"; filename="user.png"

< user.png
--WebAppBoundary--

###

POST http://{{host}}:{{port}}/sign_up
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: */*

--WebAppBoundary
Content-Type: application/json
Content-Disposition: form-data; name="user"

{
  "username": "userG",
  "password": "user",
  "email": "userG@gmail.com",
  "phoneNumber": "910000006",
  "dateOfBirth": "1998-01-01",
  "aboutMe": "I'm user G"
}
--WebAppBoundary
Content-Disposition: form-data; name="profileImage"; filename="user.png"

< user.png
--WebAppBoundary--

###

POST http://{{host}}:{{port}}/sign_up
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: */*

--WebAppBoundary
Content-Type: application/json
Content-Disposition: form-data; name="user"

{
  "username": "userH",
  "password": "user",
  "email": "userH@gmail.com",
  "phoneNumber": "910000007",
  "dateOfBirth": "1998-01-01",
  "aboutMe": "I'm user H"
}
--WebAppBoundary
Content-Disposition: form-data; name="profileImage"; filename="user.png"

< user.png
--WebAppBoundary--

###

POST http://{{host}}:{{port}}/sign_up
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: */*

--WebAppBoundary
Content-Type: application/json
Content-Disposition: form-data; name="user"

{
  "username": "userI",
  "password": "user",
  "email": "userI@gmail.com",
  "phoneNumber": "910000008",
  "dateOfBirth": "1998-01-01",
  "aboutMe": "I'm user I"
}
--WebAppBoundary
Content-Disposition: form-data; name="profileImage"; filename="user.png"

< user.png
--WebAppBoundary--

###

POST http://{{host}}:{{port}}/sign_up
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: */*

--WebAppBoundary
Content-Type: application/json
Content-Disposition: form-data; name="user"

{
  "username": "userJ",
  "password": "user",
  "email": "userJ@gmail.com",
  "phoneNumber": "910000009",
  "dateOfBirth": "1998-01-01",
  "aboutMe": "I'm user J"
}
--WebAppBoundary
Content-Disposition: form-data; name="profileImage"; filename="user.png"

< user.png
--WebAppBoundary--

###






### TOURS

POST http://{{host}}:{{port}}/sign_in
Content-Type: application/json

{
  "username": "userD",
  "password": "user"
}

> {%
    client.global.set("jwt_token", response.body);
%}

###

POST http://{{host}}:{{port}}/createTour
authorization: {{jwt_token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: */*

--WebAppBoundary
Content-Type: application/json
Content-Disposition: form-data; name="tour"

{
  "name": "Tour in Paris",
  "description": "Beautiful tour in Paris",
  "duration": "01:00:00",
  "maxCapacity": 20,
  "minCapacity": 10,
  "city": {
    "id": 2011
  },
  "category": {
    "id": 3
  },
  "guide": {
    "username": "userD"
  },
  "languages": [{
    "id": 6
  },{
    "id": 2
  }],
  "route":[{
    "name":"Paris Center",
    "description":"Paris Center",
    "longitude": 2.3470295156204557,
    "latitude": 48.85929404028656
  },
  {
    "name":"Charles de Gaulle",
    "description":"Charles de Gaulle",
    "longitude": 2.2951058290717534,
    "latitude": 48.87482058088655
  }]
}
--WebAppBoundary
Content-Disposition: form-data; name="images"; filename="paris-1.png"

< paris-1.png
--WebAppBoundary
Content-Disposition: form-data; name="images"; filename="paris-1.png"

< paris-2.png
--WebAppBoundary

###

POST http://{{host}}:{{port}}/createTour
authorization: {{jwt_token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: */*

--WebAppBoundary
Content-Type: application/json
Content-Disposition: form-data; name="tour"

{
  "name": "Tour in Rome",
  "description": "Beautiful tour in Rome",
  "duration": "01:15:00",
  "maxCapacity": 15,
  "minCapacity": 5,
  "city": {
    "id": 1125
  },
  "category": {
    "id": 4
  },
  "guide": {
    "username": "userD"
  },
  "languages": [{
    "id": 2
  }],
  "route":[{
    "name":"Colosseo",
    "description":"Colosseo",
    "longitude": 12.492450897637212 ,
    "latitude": 41.89023405530562
  }]
}
--WebAppBoundary
Content-Disposition: form-data; name="images"; filename="rome-1.png"

< rome-1.png
--WebAppBoundary
Content-Disposition: form-data; name="images"; filename="rome-2.png"

< rome-2.png
--WebAppBoundary

###

POST http://{{host}}:{{port}}/sign_in
Content-Type: application/json

{
  "username": "userB",
  "password": "user"
}

> {%
    client.global.set("jwt_token", response.body);
%}

###

POST http://{{host}}:{{port}}/createTour
authorization: {{jwt_token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: */*

--WebAppBoundary
Content-Type: application/json
Content-Disposition: form-data; name="tour"

{
  "name": "Tour in Rome",
  "description": "Beautiful tour in Rome",
  "duration": "00:45:00",
  "maxCapacity": 20,
  "minCapacity": 10,
  "city": {
    "id": 1125
  },
  "category": {
    "id": 2
  },
  "guide": {
    "username": "userB"
  },
  "languages": [{
    "id": 2
  }],
  "route":[{
    "name":"Colosseo",
    "description":"Colosseo",
    "longitude": 12.492450897637212 ,
    "latitude": 41.89023405530562
  }]
}
--WebAppBoundary
Content-Disposition: form-data; name="images"; filename="rome-3.png"

< rome-3.png
--WebAppBoundary
Content-Disposition: form-data; name="images"; filename="rome-4.png"

< rome-4.png
--WebAppBoundary

###

POST http://{{host}}:{{port}}/createTour
authorization: {{jwt_token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: */*

--WebAppBoundary
Content-Type: application/json
Content-Disposition: form-data; name="tour"

{
  "name": "Tour in Madrid",
  "description": "Beautiful tour in Madrid",
  "duration": "00:45:00",
  "maxCapacity": 15,
  "minCapacity": 8,
  "city": {
    "id": 6738
  },
  "category": {
    "id": 2
  },
  "guide": {
    "username": "userB"
  },
  "languages": [{
    "id": 3
  },{
    "id": 2
  }],
  "route":[{
    "name":"Palacio",
    "description":"Palacio",
    "longitude": -3.714751180146896,
    "latitude": 40.415456528704595
  }]
}
--WebAppBoundary
Content-Disposition: form-data; name="images"; filename="madrid-1.png"

< madrid-1.png
--WebAppBoundary
Content-Disposition: form-data; name="images"; filename="madrid-2.png"

< madrid-2.png
--WebAppBoundary

###

POST http://{{host}}:{{port}}/sign_in
Content-Type: application/json

{
  "username": "userC",
  "password": "user"
}

> {%
    client.global.set("jwt_token", response.body);
%}

###

POST http://{{host}}:{{port}}/createTour
authorization: {{jwt_token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: */*

--WebAppBoundary
Content-Type: application/json
Content-Disposition: form-data; name="tour"

{
  "name": "Tour in Tokyo",
  "description": "Beautiful tour in Tokyo",
  "duration": "00:45:00",
  "maxCapacity": 15,
  "minCapacity": 8,
  "city": {
    "id": 620
  },
  "category": {
    "id": 2
  },
  "guide": {
    "username": "userC"
  },
  "languages": [{
    "id": 2
  }],
  "route":[{
    "name":"Area 501",
    "description":"Area 501",
    "longitude": 139.75280118503395,
    "latitude": 35.69620112696844
  }]
}
--WebAppBoundary
Content-Disposition: form-data; name="images"; filename="tokyo-1.png"

< tokyo-1.png
--WebAppBoundary
Content-Disposition: form-data; name="images"; filename="tokyo-2.png"

< tokyo-2.png
--WebAppBoundary

###

POST http://{{host}}:{{port}}/createTour
authorization: {{jwt_token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: */*

--WebAppBoundary
Content-Type: application/json
Content-Disposition: form-data; name="tour"

{
  "name": "Tour in Lisbon",
  "description": "Beautiful tour in Lisbon",
  "duration": "00:30:00",
  "maxCapacity": 10,
  "minCapacity": 5,
  "city": {
    "id": 3287
  },
  "category": {
    "id": 3
  },
  "guide": {
    "username": "userC"
  },
  "languages": [{
    "id": 1
  },
  {
    "id": 2
  },
  {
    "id": 3
  }],
  "route":[{
    "name":"Parque das Nações",
    "description":"Parque das Nações",
    "longitude": -9.09487782949434,
    "latitude": 38.76505963937829
  },
  {
    "name": "Chiado",
    "description": "Chiado",
    "longitude": -9.140796322337378,
    "latitude": 38.71032837941321 
  }]
}
--WebAppBoundary
Content-Disposition: form-data; name="images"; filename="lisbon-1.png"

< lisbon-1.png
--WebAppBoundary
Content-Disposition: form-data; name="images"; filename="lisbon-2.png"

< lisbon-2.png
--WebAppBoundary

###

POST http://{{host}}:{{port}}/createTour
authorization: {{jwt_token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: */*

--WebAppBoundary
Content-Type: application/json
Content-Disposition: form-data; name="tour"

{
  "name": "Tour in Barcelona",
  "description": "Beautiful tour in Barcelona",
  "duration": "00:30:00",
  "maxCapacity": 10,
  "minCapacity": 5,
  "city": {
    "id": 4466
  },
  "category": {
    "id": 2
  },
  "guide": {
    "username": "userC"
  },
  "languages": [{
    "id": 3
  },{
    "id": 2
  }],
  "route":[{
    "name":"Camp Nou",
    "description":"Camp Nou",
    "longitude": 2.1233958215358677,
    "latitude": 41.380801585315346
  }]
}
--WebAppBoundary
Content-Disposition: form-data; name="images"; filename="barcelona-1.png"

< barcelona-1.png
--WebAppBoundary
Content-Disposition: form-data; name="images"; filename="barcelona-2.png"

< barcelona-2.png
--WebAppBoundary

###

POST http://{{host}}:{{port}}/createTour
authorization: {{jwt_token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: */*

--WebAppBoundary
Content-Type: application/json
Content-Disposition: form-data; name="tour"

{
  "name": "Come visit Messi",
  "description": "Beautiful tour in Barcelona",
  "duration": "00:45:00",
  "maxCapacity": 15,
  "minCapacity": 8,
  "city": {
    "id": 4466
  },
  "category": {
    "id": 2
  },
  "guide": {
    "username": "userC"
  },
  "languages": [{
    "id": 3
  },{
    "id": 2
  }],
  "route":[{
    "name":"Camp Nou",
    "description":"Camp Nou",
    "longitude": 2.1233958215358677,
    "latitude": 41.380801585315346
  }]
}
--WebAppBoundary
Content-Disposition: form-data; name="images"; filename="barcelona-1.png"

< barcelona-1.png
--WebAppBoundary
Content-Disposition: form-data; name="images"; filename="barcelona-2.png"

< barcelona-2.png
--WebAppBoundary

###